name: SpectralOps
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Preflight
        uses: SpectralOps/setup-preflight-action@v1
        with:
          preflight-version: "1.1.4"
      - name: Spectral Install
        run: curl -L "https://spectral-eu.checkpoint.com/latest/x/sh?dsn=${SPECTRAL_DSN}" | sh
      - name: Spectral Scan
        run:  $HOME/.spectral/spectral scan --ok --engines secrets,iac,oss --include-tags base,audit3,iac --sarif
      - uses: actions/upload-artifact@v4
        with:
          name: spectral-report
          path: output.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: output.sarif           
